import { Hono } from "hono";
import type { Context } from "hono";
import type { DashboardSummary, TransactionType } from "../shared/types";
import {
  clearSession,
  currentUserId,
  issueSession,
  requireAuth,
} from "./auth";
import { hashPassword, verifyPassword } from "./password";
import { validateTransaction, validateCredentials, isValidMonth } from "./validation";
import * as db from "./db";

// `Env` is generated by `wrangler types`. `Variables` is what requireAuth sets.
export type AppEnv = { Bindings: Env; Variables: { userId: string } };

const app = new Hono<AppEnv>();

// ---------------------------------------------------------------------------
// Health + auth (public)
// ---------------------------------------------------------------------------

app.get("/api/health", (c) =>
  c.json({ status: "ok", time: new Date().toISOString() }),
);

app.post("/api/auth/register", async (c) => {
  const valid = validateCredentials(await c.req.json().catch(() => null));
  if (!valid.ok) return c.json({ error: valid.error }, 400);
  const passwordHash = await hashPassword(valid.value.password);
  const user = await db.createUser(c.env.DB, valid.value.email, passwordHash);
  if (!user) return c.json({ error: "Email already registered" }, 409);
  await issueSession(c, user.id);
  return c.json({ user }, 201);
});

app.post("/api/auth/login", async (c) => {
  const valid = validateCredentials(await c.req.json().catch(() => null));
  if (!valid.ok) return c.json({ error: valid.error }, 400);
  const row = await db.getUserByEmail(c.env.DB, valid.value.email);
  // Always run a verify to keep timing roughly constant even when no user.
  const ok = row
    ? await verifyPassword(valid.value.password, row.password_hash)
    : await verifyPassword(valid.value.password, "pbkdf2$100000$x$y");
  if (!row || !ok) return c.json({ error: "Invalid email or password" }, 401);
  await issueSession(c, row.id);
  return c.json({ user: { id: row.id, email: row.email } });
});

app.post("/api/auth/logout", (c) => {
  clearSession(c);
  return c.json({ ok: true });
});

// Used by the frontend on load to know who (if anyone) is logged in.
app.get("/api/me", async (c) => {
  const userId = await currentUserId(c);
  if (!userId) return c.json({ user: null });
  const user = await db.getUserById(c.env.DB, userId);
  return c.json({ user });
});

// ---------------------------------------------------------------------------
// Everything below requires a valid session. requireAuth puts userId on ctx.
// ---------------------------------------------------------------------------

const api = new Hono<AppEnv>();
api.use("*", requireAuth);

async function knownCategorySet(
  database: D1Database,
  userId: string,
): Promise<Set<string>> {
  const cats = await db.listCategories(database, userId);
  return new Set(cats.map((x) => x.name));
}

// ---- categories ----

api.get("/categories", async (c) => {
  const categories = await db.listCategories(c.env.DB, c.get("userId"));
  return c.json({ categories });
});

api.post("/categories", async (c) => {
  const body = (await c.req.json().catch(() => null)) as {
    type?: unknown;
    name?: unknown;
    icon?: unknown;
  } | null;
  if (body?.type !== "income" && body?.type !== "expense")
    return c.json({ error: "type must be income or expense" }, 400);
  if (typeof body.name !== "string" || body.name.trim() === "")
    return c.json({ error: "name is required" }, 400);
  const icon = typeof body.icon === "string" ? body.icon.slice(0, 8) : null;
  const created = await db.createCategory(
    c.env.DB,
    c.get("userId"),
    body.type,
    body.name.trim().toLowerCase().replace(/\s+/g, "_").slice(0, 40),
    icon,
  );
  if (!created) return c.json({ error: "Category already exists" }, 409);
  return c.json({ category: created }, 201);
});

api.delete("/categories/:id", async (c) => {
  const ok = await db.deleteCategory(c.env.DB, c.get("userId"), c.req.param("id"));
  return ok ? c.json({ ok: true }) : c.json({ error: "Not found" }, 404);
});

// ---- transactions CRUD ----

function parseFilters(c: Context<AppEnv>): db.TxFilters {
  const q = c.req.query();
  const type =
    q.type === "income" || q.type === "expense"
      ? (q.type as TransactionType)
      : undefined;
  return {
    type,
    category: q.category || undefined,
    search: q.search || undefined,
    start: q.start || undefined,
    end: q.end || undefined,
    limit: q.limit ? Number(q.limit) : undefined,
    offset: q.offset ? Number(q.offset) : undefined,
  };
}

api.get("/transactions", async (c) => {
  const userId = c.get("userId");
  const filters = parseFilters(c);
  const [transactions, total] = await Promise.all([
    db.listTransactions(c.env.DB, userId, filters),
    db.countTransactions(c.env.DB, userId, filters),
  ]);
  return c.json({ transactions, total });
});

api.post("/transactions", async (c) => {
  const userId = c.get("userId");
  const body = await c.req.json().catch(() => null);
  const valid = validateTransaction(body, await knownCategorySet(c.env.DB, userId));
  if (!valid.ok) return c.json({ error: valid.error }, 400);
  const created = await db.createTransaction(c.env.DB, userId, valid.value);
  return c.json({ transaction: created }, 201);
});

api.put("/transactions/:id", async (c) => {
  const userId = c.get("userId");
  const body = await c.req.json().catch(() => null);
  const valid = validateTransaction(body, await knownCategorySet(c.env.DB, userId));
  if (!valid.ok) return c.json({ error: valid.error }, 400);
  const updated = await db.updateTransaction(
    c.env.DB,
    userId,
    c.req.param("id"),
    valid.value,
  );
  return updated
    ? c.json({ transaction: updated })
    : c.json({ error: "Not found" }, 404);
});

api.delete("/transactions/:id", async (c) => {
  const ok = await db.deleteTransaction(
    c.env.DB,
    c.get("userId"),
    c.req.param("id"),
  );
  return ok ? c.json({ ok: true }) : c.json({ error: "Not found" }, 404);
});

// ---- dashboard ----

function currentMonth(): string {
  return new Date().toISOString().slice(0, 7);
}

function daysInMonth(month: string): number {
  const [y, m] = month.split("-").map(Number);
  return new Date(y, m, 0).getDate();
}

api.get("/dashboard", async (c) => {
  const userId = c.get("userId");
  const month = c.req.query("month");
  const m = month && isValidMonth(month) ? month : currentMonth();
  const [{ income, expense }, top, totalCount] = await Promise.all([
    db.getMonthTotals(c.env.DB, userId, m),
    db.getTopExpenseCategory(c.env.DB, userId, m),
    db.getTotalCount(c.env.DB, userId),
  ]);
  // Average daily spend: current month -> divide by days elapsed so far,
  // past month -> divide by full days in that month.
  const divisor =
    m === currentMonth() ? new Date().getUTCDate() : daysInMonth(m);
  const summary: DashboardSummary = {
    month: m,
    income,
    expense,
    balance: income - expense,
    avgExpensePerDay:
      divisor > 0 ? Math.round((expense / divisor) * 100) / 100 : 0,
    topCategory: top,
    totalCount,
  };
  return c.json(summary);
});

// ---- reports ----

api.get("/reports/monthly", async (c) => {
  const limit = c.req.query("limit") ? Number(c.req.query("limit")) : 12;
  const months = await db.getMonthlyReport(c.env.DB, c.get("userId"), limit);
  return c.json({ months });
});

api.get("/reports/categories", async (c) => {
  const month = c.req.query("month");
  const m = month && isValidMonth(month) ? month : undefined;
  const type = c.req.query("type") === "income" ? "income" : "expense";
  const breakdown = await db.getCategoryBreakdown(
    c.env.DB,
    c.get("userId"),
    type,
    m,
  );
  return c.json({ breakdown });
});

// ---- CSV export ----

function csvCell(value: unknown): string {
  const s = value == null ? "" : String(value);
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

api.get("/export.csv", async (c) => {
  const rows = await db.listTransactions(c.env.DB, c.get("userId"), {
    ...parseFilters(c),
    limit: 1000,
  });
  const header = ["date", "type", "category", "description", "amount"];
  const lines = [header.join(",")];
  for (const r of rows) {
    lines.push(
      [r.transaction_date, r.type, r.category, csvCell(r.description), r.amount].join(
        ",",
      ),
    );
  }
  // UTF-8 BOM so Excel renders Thai text correctly.
  const csv = "﻿" + lines.join("\n");
  return new Response(csv, {
    headers: {
      "Content-Type": "text/csv; charset=utf-8",
      "Content-Disposition": `attachment; filename="transactions.csv"`,
    },
  });
});

app.route("/api", api);

app.notFound((c) => c.json({ error: "Not found" }, 404));

export default app;