import { Hono } from "hono";
import type { Context } from "hono";
import type {
  DashboardSummary,
  TransactionType,
} from "../shared/types";
import {
  checkPassword,
  clearSession,
  isAuthenticated,
  issueSession,
  requireAuth,
} from "./auth";
import { validateTransaction, isValidMonth } from "./validation";
import * as db from "./db";

// `Env` is generated by `wrangler types` into worker-configuration.d.ts.
export type AppEnv = { Bindings: Env };

const app = new Hono<AppEnv>();

// ---------------------------------------------------------------------------
// Health + auth (public)
// ---------------------------------------------------------------------------

app.get("/api/health", (c) =>
  c.json({ status: "ok", time: new Date().toISOString() }),
);

app.post("/api/login", async (c) => {
  const body = await c.req.json().catch(() => null);
  const password = (body as { password?: unknown } | null)?.password;
  if (typeof password !== "string" || !checkPassword(password, c.env.ADMIN_PASSWORD)) {
    return c.json({ error: "Invalid password" }, 401);
  }
  await issueSession(c);
  return c.json({ ok: true });
});

app.post("/api/logout", (c) => {
  clearSession(c);
  return c.json({ ok: true });
});

// Used by the frontend on load to know if the cookie is still valid.
app.get("/api/me", async (c) => {
  return c.json({ authenticated: await isAuthenticated(c) });
});

// ---------------------------------------------------------------------------
// Everything below requires a valid session.
// ---------------------------------------------------------------------------

const api = new Hono<AppEnv>();
api.use("*", requireAuth);

// ---- categories ----

api.get("/categories", async (c) => {
  const categories = await db.listCategories(c.env.DB);
  return c.json({ categories });
});

api.post("/categories", async (c) => {
  const body = (await c.req.json().catch(() => null)) as {
    type?: unknown;
    name?: unknown;
    icon?: unknown;
  } | null;
  if (body?.type !== "income" && body?.type !== "expense")
    return c.json({ error: "type must be income or expense" }, 400);
  if (typeof body.name !== "string" || body.name.trim() === "")
    return c.json({ error: "name is required" }, 400);
  const icon = typeof body.icon === "string" ? body.icon.slice(0, 8) : null;
  const created = await db.createCategory(
    c.env.DB,
    body.type,
    body.name.trim().toLowerCase().replace(/\s+/g, "_").slice(0, 40),
    icon,
  );
  if (!created) return c.json({ error: "Category already exists" }, 409);
  return c.json({ category: created }, 201);
});

api.delete("/categories/:id", async (c) => {
  const ok = await db.deleteCategory(c.env.DB, c.req.param("id"));
  return ok ? c.json({ ok: true }) : c.json({ error: "Not found" }, 404);
});

// Build a known-category allow-list (defaults + custom) for validation.
async function knownCategorySet(database: D1Database): Promise<Set<string>> {
  const cats = await db.listCategories(database);
  return new Set(cats.map((x) => x.name));
}

// ---- transactions CRUD ----

function parseFilters(c: Context<AppEnv>): db.TxFilters {
  const q = c.req.query();
  const type =
    q.type === "income" || q.type === "expense"
      ? (q.type as TransactionType)
      : undefined;
  return {
    type,
    category: q.category || undefined,
    search: q.search || undefined,
    start: q.start || undefined,
    end: q.end || undefined,
    limit: q.limit ? Number(q.limit) : undefined,
    offset: q.offset ? Number(q.offset) : undefined,
  };
}

api.get("/transactions", async (c) => {
  const filters = parseFilters(c);
  const [transactions, total] = await Promise.all([
    db.listTransactions(c.env.DB, filters),
    db.countTransactions(c.env.DB, filters),
  ]);
  return c.json({ transactions, total });
});

api.post("/transactions", async (c) => {
  const body = await c.req.json().catch(() => null);
  const valid = validateTransaction(body, await knownCategorySet(c.env.DB));
  if (!valid.ok) return c.json({ error: valid.error }, 400);
  const created = await db.createTransaction(c.env.DB, valid.value);
  return c.json({ transaction: created }, 201);
});

api.put("/transactions/:id", async (c) => {
  const body = await c.req.json().catch(() => null);
  const valid = validateTransaction(body, await knownCategorySet(c.env.DB));
  if (!valid.ok) return c.json({ error: valid.error }, 400);
  const updated = await db.updateTransaction(
    c.env.DB,
    c.req.param("id"),
    valid.value,
  );
  return updated
    ? c.json({ transaction: updated })
    : c.json({ error: "Not found" }, 404);
});

api.delete("/transactions/:id", async (c) => {
  const ok = await db.deleteTransaction(c.env.DB, c.req.param("id"));
  return ok ? c.json({ ok: true }) : c.json({ error: "Not found" }, 404);
});

// ---- dashboard ----

function currentMonth(): string {
  return new Date().toISOString().slice(0, 7);
}

function daysInMonth(month: string): number {
  const [y, m] = month.split("-").map(Number);
  return new Date(y, m, 0).getDate();
}

api.get("/dashboard", async (c) => {
  const month = c.req.query("month");
  const m = month && isValidMonth(month) ? month : currentMonth();
  const [{ income, expense }, top, totalCount] = await Promise.all([
    db.getMonthTotals(c.env.DB, m),
    db.getTopExpenseCategory(c.env.DB, m),
    db.getTotalCount(c.env.DB),
  ]);
  // Average daily spend: for the current month divide by days elapsed so far,
  // for a past month divide by the full number of days in that month.
  const today = new Date();
  const divisor =
    m === currentMonth() ? today.getUTCDate() : daysInMonth(m);
  const summary: DashboardSummary = {
    month: m,
    income,
    expense,
    balance: income - expense,
    avgExpensePerDay: divisor > 0 ? Math.round((expense / divisor) * 100) / 100 : 0,
    topCategory: top,
    totalCount,
  };
  return c.json(summary);
});

// ---- reports ----

api.get("/reports/monthly", async (c) => {
  const limit = c.req.query("limit") ? Number(c.req.query("limit")) : 12;
  const months = await db.getMonthlyReport(c.env.DB, limit);
  return c.json({ months });
});

api.get("/reports/categories", async (c) => {
  const month = c.req.query("month");
  const m = month && isValidMonth(month) ? month : undefined;
  const type =
    c.req.query("type") === "income" ? "income" : "expense";
  const breakdown = await db.getCategoryBreakdown(c.env.DB, type, m);
  return c.json({ breakdown });
});

// ---- CSV export ----

function csvCell(value: unknown): string {
  const s = value == null ? "" : String(value);
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

api.get("/export.csv", async (c) => {
  const rows = await db.listTransactions(c.env.DB, {
    ...parseFilters(c),
    limit: 1000,
  });
  const header = ["date", "type", "category", "description", "amount"];
  const lines = [header.join(",")];
  for (const r of rows) {
    lines.push(
      [
        r.transaction_date,
        r.type,
        r.category,
        csvCell(r.description),
        r.amount,
      ].join(","),
    );
  }
  // UTF-8 BOM so Excel renders Thai text correctly.
  const csv = "﻿" + lines.join("\n");
  return new Response(csv, {
    headers: {
      "Content-Type": "text/csv; charset=utf-8",
      "Content-Disposition": `attachment; filename="transactions.csv"`,
    },
  });
});

app.route("/api", api);

app.notFound((c) => c.json({ error: "Not found" }, 404));

export default app;
